# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2752bb8b8bd58871741f838b7f401592e3bfb57e3d3a93fc42bfc7f96f1ff0154657d3d9f456e0f162ceb96595d1da1c72739b512f9df64c136488f0107dae75

test:
  secret_key_base: 2e692cdd9c8fe239f321f836ec3df3b325243a021c6865f4d607d7f425de9bbceba914c2aaf5927b7db0d577dab07039b3ce09bd89a30e46a7983e49c0ede125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
